# utils/exceptions.py

class ConnectionLostError(Exception):
    """Exception raised when connection to the Arduino is lost."""
    pass
